SELECT * FROM VENDORS
LEFT JOIN PARTS ON PARTS.PART_VENDORID = VENDORS.VEN_ID 
WHERE PARTS.PART_VENDORID IS NULL

DELETE VENDORS FROM VENDORS
LEFT JOIN PARTS ON PARTS.PART_VENDORID = VENDORS.VEN_ID 
WHERE PARTS.PART_VENDORID IS NULL

UPDATE PARTS SET PART_CATEGORYID = 501 WHERE PART_ID= 2

INSERT INTO CATEGORIES (CAT_ID,CAT_NAME, CAT_TYPE) VALUES (701,'Styling','D')